# $ kubectl create -f etcd-operator-crd.yaml
# customresourcedefinition.apiextensions.k8s.io/etcdclusters.etcd.database.coreos.com created
#
# $ kubectl get crd
# NAME                                    CREATED AT
# etcdclusters.etcd.database.coreos.com   2023-03-15T07:39:21Z
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: etcdclusters.etcd.database.coreos.com
spec:
  group: etcd.database.coreos.com
  names:
    kind: EtcdCluster
    listKind: EtcdClusterList
    plural: etcdclusters
    shortNames:
      - etcdclus
      - etcd
    singular: etcdcluster
  scope: Namespaced
  versions:
    - name: v1beta2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                spec:
                  type: object
                  properties:
                    size:
                      type: integer
                    version:
                      type: string
