# $ kubectl create -f etcd-operator-rolebinding.yaml
# rolebinding.rbac.authorization.k8s.io/etcd-operator-rolebinding created
#
# $ kubectl get rolebindings
# NAME                        ROLE                      AGE
# etcd-operator-rolebinding   Role/etcd-operator-role   26s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-operator-role
subjects:
  - kind: ServiceAccount
    name: etcd-operator-sa
    namespace: default
